# Generated by Django 6.1.1 on 2026-09-27 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('instrucciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_juego', models.CharField(choices=[('seleccion', 'Seleccion multiple (branding,Contraste, HEX)'), ('mezcla', 'Mezcla de colores (Matraces)'), ('rgb', 'Laboratorio RGB'), ('drag_drop', 'Arrastrar y soltar(Temperatura,Saturacion)')], max_length=20)),
                ('pregunta_objetivo', models.CharField(max_length=255)),
                ('configuracion', models.JSONField(default=dict, help_text='Configuración específica del desafío')),
                ('respuesta_correcta', models.CharField(max_length=100)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niveles.nivel')),
            ],
        ),
    ]
